# Generated by Django 4.2.1 on 2023-05-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
