# Generated by Django 4.2.1 on 2023-05-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
